name: Entrega Continua

on:
  workflow_call:

jobs:

  ec2:
    runs-on: ubuntu-latest
        
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        # Artifact name
        name: app
     - uses: actions/checkout@v3
